%%% This file was automatically generated by snmpc_mib_to_hrl version 4.21.1
%%% Date: 24-Oct-2012::15:56:54
-ifndef('DHT-MIB').
-define('DHT-MIB', true).

%% Oids

-define(dht, [1,3,6,1,4,1,88888,1,1,1]).

-define(dhtTable, [1,3,6,1,4,1,88888,1,1,1,1]).

-define(dhtEntry, [1,3,6,1,4,1,88888,1,1,1,1,1]).
-define(nodeName, 1).
-define(handoffTimeouts, 2).
-define(nodeGetsTotal, 3).
-define(nodePutsTotal, 4).
-define(cpuAvg15, 5).
-define(nodeGetFsmTimeMedian, 6).
-define(nodePutFsmTimeMedian, 7).
-define(dhtStatus, 8).


%% Range values
-define(low_nodeName, 0).
-define(high_nodeName, 255).


%% Enum definitions from dhtStatus
-define(dhtStatus_destroy, 6).
-define(dhtStatus_createAndWait, 5).
-define(dhtStatus_createAndGo, 4).
-define(dhtStatus_notReady, 3).
-define(dhtStatus_notInService, 2).
-define(dhtStatus_active, 1).

%% Default values

-endif.
