%%% This file was automatically generated by snmpc_mib_to_hrl version 4.22.1
%%% Date: 22-Oct-2012::18:24:34
-ifndef('DHT-MIB').
-define('DHT-MIB', true).

%% Oids

%-define(paynet, [1,3,6,1,4,1,88888]).

-define(dhtTable, [1,3,6,1,4,1,88888,1]).

-define(dhtEntry, [1,3,6,1,4,1,88888,1,1]).
-define(dName, 1).
-define(reqPerSec, 2).
-define(dhtStatus, 3).


%% Range values
-define(low_dName, 0).
-define(high_dName, 255).


%% Enum definitions from dhtStatus
-define(dhtStatus_destroy, 6).
-define(dhtStatus_createAndWait, 5).
-define(dhtStatus_createAndGo, 4).
-define(dhtStatus_notReady, 3).
-define(dhtStatus_notInService, 2).
-define(dhtStatus_active, 1).

%% Default values

-endif.
