%%% This file was automatically generated by snmpc_mib_to_hrl version 4.22.1
%%% Date: 22-Oct-2012::18:24:29
-ifndef('GAME-MIB').
-define('GAME-MIB', true).

%% Oids

-define(paynet, [1,3,6,1,4,1,88888]).

-define(gameTable, [1,3,6,1,4,1,88888,2]).

-define(gameEntry, [1,3,6,1,4,1,88888,2,1]).
-define(gName, 1).
-define(online, 2).
-define(gStatus, 3).


%% Range values
-define(low_gName, 0).
-define(high_gName, 255).


%% Enum definitions from gStatus
-define(gStatus_destroy, 6).
-define(gStatus_createAndWait, 5).
-define(gStatus_createAndGo, 4).
-define(gStatus_notReady, 3).
-define(gStatus_notInService, 2).
-define(gStatus_active, 1).

%% Default values

-endif.
