%%% This file was automatically generated by snmpc_mib_to_hrl version 4.22.1
%%% Date: 23-Oct-2012::21:46:58
-ifndef('KAKA-REG').
-define('KAKA-REG', true).

%% Oids

-define(paynet, [1,3,6,1,4,1,88888]).

-define(kakaranet, [1,3,6,1,4,1,88888,1]).

-define(kakaSquares, [1,3,6,1,4,1,88888,1,1]).


%% Range values


%% Default values

-endif.
