-define(APPSERVER_NODE, nsx_opt:get_env(nsw_srv,app_srv_node, 'app@rigdzin.cc')).
-define(GAMESRVR_NODE, nsx_opt:get_env(nsw_srv,game_srv_node, 'game@rigdzin.cc')).
-define(FORGET_TOKEN_EXPIRED, 86400).
-define(INVITE_CODE_EXPIRED, 172800). %% 48h
-define(FB_REDIRECT_URI, lists:flatten(io_lib:format("~s/?facebook=true", [?HTTP_ADDRESS]))).
-define(FB_LOGIN_LINK, lists:concat(["https://www.facebook.com/dialog/oauth?client_id=", ?FB_APP_ID, "&redirect_uri="])).
-define(SERVER_PORT, nsx_opt:get_env(nsw_srv,game_srv_port, 7999)).
-define(SERVER_HOST, nsx_opt:get_env(nsw_srv, game_srv_host, "kakaranet.com")).
-define(FB_APP_ID, nsx_opt:get_env(nsw_srv,fb_id, "154227314626053")).
-define(FB_APP_SECRET, nsx_opt:get_env(nsw_srv,fb_secret, "cf9d49958ee536dd75f15bf8ca541965")).
-define(HTTP_ADDRESS, nsx_opt:get_env(nsw_srv,http_address, "http://kakaranet.com:7788")).
-define(FEED_PAGEAMOUNT, 20).
