-define(MAX_BAD_OPERATION, 5).
-define(SMTP_USER, nsm_db:get_config("smtp/user",     "noreply@kakaranet.com")).
-define(SMTP_PASSWD, nsm_db:get_config("smtp/password", "unknown")).
-define(SMTP_HOST, nsm_db:get_config("smtp/host",     "smtp.kakaranet.com")).
-define(SMTP_PORT, nsm_db:get_config("smtp/port",     587)).
-define(SMTP_SSL, nsm_db:get_config("smtp/with_ssl", false)).
