DHT-MIB DEFINITIONS ::= BEGIN

IMPORTS
    OBJECT-TYPE
	FROM SNMPv2-SMI
    DisplayString
	FROM SNMPv2-TC
    RowStatus
	FROM STANDARD-MIB
    kakaSquares
	FROM KAKA-REG;

dht OBJECT IDENTIFIER ::= { kakaSquares 1}

dhtTable OBJECT-TYPE
    SYNTAX SEQUENCE OF DHTEntry
    ACCESS not-accessible
    STATUS mandatory
    DESCRIPTION "Table of servers DHT information."
    ::= { dht 1 }

dhtEntry OBJECT-TYPE
    SYNTAX DHTEntry
    ACCESS not-accessible
    STATUS mandatory
    DESCRIPTION        "An entry in dhtTable"
    INDEX   { dName }    ::= { dhtTable 1 }

DHTEntry ::= SEQUENCE {
    dName DisplayString,
    nodeGets INTEGER,
    nodePuts INTEGER,
    dhtStatus RowStatus}

dName OBJECT-TYPE
    SYNTAX DisplayString
    ACCESS read-only
    STATUS mandatory
    DESCRIPTION "Server name. Used as index for dhtTable."
    ::= { dhtEntry 1 }

nodeGets OBJECT-TYPE
    SYNTAX INTEGER
    ACCESS  read-write
    STATUS  mandatory
    DESCRIPTION "Number of Gets coordinated by this node within last minute."
    ::= { dhtEntry 2 }

nodePuts OBJECT-TYPE
    SYNTAX INTEGER
    ACCESS  read-write
    STATUS  mandatory
    DESCRIPTION "Number of Puts coordinated by this node within last minute."
    ::= { dhtEntry 3 }

dhtStatus OBJECT-TYPE
    SYNTAX RowStatus
    ACCESS  read-write
    STATUS  mandatory
    DESCRIPTION "The status of this row."
    ::= { dhtEntry 4 }

END
